### ISSUE TITLE
pass arguments in commands

### ISSUE THREAD

**Issue by jmecosta** [David-Desmaisons/Neutronium#4]
hi David,

i have a d3 force plot, that user picks a node. Once this happens the javascript update a input html displaying the node name.

this input is hidden, and has the following data-bind
<input id="SelectedNodeId2" data-bind="value:SelectedNodeInD3" placeholder="Type" visibility="hidden" />

in js i set the value like this
$('#SelectedNodeId2').val(d.name);

I was expecting, that this value would be available in my view model in c#, but its not. Also if i press a command like this:

<button data-bind="execute: $root.RemoveSkill, executeoption: { callback : function(){alert('removing');} }">Remove skill</button>

the RemoveSkill in C# is called but the value of the SelectedNodeId2 is not updated.

If i dont set the value from the js, and set it via the ui (when its visible), then when i can see the value after i press the command.

Is there a way of binding from a js function and from c# function so the javascript can communicate with the c# without using the html?

thanks in advance
br

jorge costa

**Comment by David-Desmaisons** [comment]
hello @jmecosta ,

Yes, you can access the vm in javascript and change its value.
Let's say that vm is you main view model.
You can call:
```javascript
vm.Name('newName');
```

this will update the corresponding property in the C# viewModel with the expected "newName" value.

It will be nice if you could share som screen-shot of your neutronium project once it is done. I am thinking of adding sample application screen-shot in the github readme.

PS: You should try vue.js binding I am about to release powerfull tools.

**Comment by David-Desmaisons** [comment]
If you want to call a command, from javascript:

```javascript
vm.MyCommand().Execute('myValue')
```

It will call the corresponing C# command, with "myValue" Argument

**Comment by jmecosta** [comment]
hi David,

ive move to vue.js now,

having a bit of troubles to understand how i woul get a already defined main view model. In doc we have main view model under <div id="main">

so i would like to call something like:
$('#main').data.MyCommand().Execute('myValue')

If i do 
    var vm = new Vue({
        el: '#main',
        data: {
            DataElement: 'Hello Vue!'
        }
    })

i can assess the data in the ui, however i cannot access the relevant command in the c# side, i supose it gets overriten.

PS: this is the first time i play with both Vue.js, so thanks for the help

**Comment by David-Desmaisons** [comment]
Well, it all depends on the scenario and what you finally want to achieve. I am not clear, what should be the trigger to run the command,

In any cases, the best way to arquitecture your code is to trigger the call to the command in a vue method (meaning a method defined in the view model) where you will have full access to all the data:

```javascript
methods:{
   callCommand(){
       this.MyCommand.Execute("ddd")
   }
}
```

If you want me to provide more insights on potenciakl solution,  I will need sample code and a more precise case of want you want to achieve.

**Comment by jmecosta** [comment]
@David-Desmaisons thanks for the hint, it helped i ended up getting it work like this:

```
    const localMixin = {
        data: {
        },
        methods: {
            BuildNode: function () {
                var self = this;
                this.BuildNode.Execute($('#SelectedNodeId').text());
            }
        }
    };

    Vue._vmMixin = [localMixin];
```

not sure if that the best approach but it works.

regarding the screenshots, this is for a internal tool we use to build our code with msbuild. When i have a bit of more time i can try to create a generic tool for msbuild. if you want i can past some screenshots, but not sure if they are usefull to others

**Comment by David-Desmaisons** [comment]
@jmecosta , glad to see it worked.
Regarding the screenshot, the idea is basically to share some project made using Neutrnium.
